server:
  port: 8080
  servlet:
    context-path: /api
  address: 0.0.0.0

spring:
  application:
    name: R-Note

  # 在db_credential.yml填写用户信息
  config:
    # 两种数据库配置文件位置，按需更改
    import:
      # 基于classpath,硬编码
      - classpath:config/db_credential.yml
      # 基于外部文件
      # - optional:file:config/db_credential.yml

  datasource:
    druid:
      auth-db:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/auth_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: ${auth_db.username}
        password: ${auth_db.password}
        initial-size: 3        # 连接池初始大小
        max-active: 10         # 最大连接数
        min-idle: 3            # 最小空闲连接
        max-wait: 60000        # 获取连接最大等待时间 (毫秒)

      note-db:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/note_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: ${note_db.username}
        password: ${note_db.password}
        initial-size: 3
        max-active: 10
        min-idle: 3
        max-wait: 60000

      # 监控相关
      filters: stat,wall,slf4j
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        url-pattern: /*

  # Jackson JSON 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  jta:
    enabled: true

    # atomikos配置
    atomikos:
      properties:
        transaction-manager-unique-name: txManager
        enable-logging: true
        log-base-dir: logs/atom-logs
      datasource:
        auth:
          min-pool-size: 5
          max-pool-size: 20
          borrow-connection-timeout: 60
          max-lifetime: 600000

        note:
          min-pool-size: 5
          max-pool-size: 20
          borrow-connection-timeout: 60
          max-lifetime: 600000

logging:
  config: classpath:config/logback-spring.xml

# MyBatis 配置 ，使用mybatis-config.xml进一步配置
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath*:mapper/**/*.xml
